version: 2.1

orbs:
  android: circleci/android@1.0

commands:
  restore_gradle_cache:
    description: "Restore gradle cache"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
            - v1-dependencies-

  save_gradle_cache:
    description: "Save gradle cache"
    steps:
      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.gradle"
            - "~/.m2"
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}

jobs:
  test:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_gradle_cache
      - run: ./gradlew androidDependencies
      - save_gradle_cache
      - run: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  lint:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_gradle_cache
      - run: ./gradlew androidDependencies
      - save_gradle_cache
      - run: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  pipeline:
    jobs:
      - test
      - lint
      - android/run-ui-tests:
          system-image: system-images;android-30;default;x86
