version: 2

commands:
  restore_gradle_cache:
    description: "Restore gradle cache"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

  save_gradle_cache:
    description: "Save gradle cache"
    steps:
      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.gradle"
            - "~/.m2"
          key: v1-dependencies-{{ checksum "build.gradle" }}

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_gradle_cache
      - run: gradle dependencies
      - save_gradle_cache
      - run: gradle check
      - store_artifacts:
          path: ~/repo/app/build/reports/tests
      - store_test_results:
          path: ~/repo/app/build/reports/tests

  lint:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_gradle_cache
      - run: gradle dependencies
      - save_gradle_cache
      - run: gradle lint
      - store_artifacts:
          path: ~/repo/app/build/reports
      - store_test_results:
          path: ~/repo/app/build/reports

workflows:
  pipeline:
    jobs:
      - test
      - lint
